import React from "react";

export const skillHoverColors: Record<string, string> = {
  Python: "hover:text-[#3776AB] hover:shadow-[0_0_20px_rgba(55,118,171,0.2)]",
  C: "hover:text-[#A8B9CC] hover:shadow-[0_0_20px_rgba(168,185,204,0.2)]",
  "C++": "hover:text-[#00599C] hover:shadow-[0_0_20px_rgba(0,89,156,0.2)]",
  JavaScript: "hover:text-[#F7DF1E] hover:shadow-[0_0_20px_rgba(247,223,30,0.2)]",
  TypeScript: "hover:text-[#3178C6] hover:shadow-[0_0_20px_rgba(49,120,198,0.2)]",
  React: "hover:text-[#61DAFB] hover:shadow-[0_0_20px_rgba(97,218,251,0.2)]",
  "Next.js": "hover:text-[#FFFFFF] hover:shadow-[0_0_20px_rgba(255,255,255,0.15)]",
  "Node.js": "hover:text-[#339933] hover:shadow-[0_0_20px_rgba(51,153,51,0.2)]",
  PyTorch: "hover:text-[#EE4C2C] hover:shadow-[0_0_20px_rgba(238,76,44,0.2)]",
  TensorFlow: "hover:text-[#FF9900] hover:shadow-[0_0_20px_rgba(255,153,0,0.2)]",
  FastAPI: "hover:text-[#009688] hover:shadow-[0_0_20px_rgba(0,150,136,0.2)]",
  SQL: "hover:text-[#00758F] hover:shadow-[0_0_20px_rgba(0,117,143,0.2)]",
  PostgreSQL: "hover:text-[#4169E1] hover:shadow-[0_0_20px_rgba(65,105,225,0.2)]",
  "Tailwind CSS": "hover:text-[#06B6D4] hover:shadow-[0_0_20px_rgba(6,182,212,0.2)]",
  Figma: "hover:text-[#F24E1E] hover:shadow-[0_0_20px_rgba(242,78,30,0.2)]",
  Docker: "hover:text-[#2496ED] hover:shadow-[0_0_20px_rgba(36,150,237,0.2)]",
  AWS: "hover:text-[#FF9900] hover:shadow-[0_0_20px_rgba(255,153,0,0.2)]",
  Git: "hover:text-[#F05032] hover:shadow-[0_0_20px_rgba(240,80,50,0.2)]",
  Github: "hover:text-[#FFFFFF] hover:shadow-[0_0_20px_rgba(255,255,255,0.15)]",
};

export const skillLogos: Record<string, React.ReactNode> = {
  Python: <img src="https://skillicons.dev/icons?i=py" alt="Python" className="w-full h-full" />,
  C: <img src="https://skillicons.dev/icons?i=c" alt="C" className="w-full h-full" />,
  "C++": <img src="https://skillicons.dev/icons?i=cpp" alt="C++" className="w-full h-full" />,
  JavaScript: <img src="https://skillicons.dev/icons?i=js" alt="JavaScript" className="w-full h-full" />,
  TypeScript: <img src="https://skillicons.dev/icons?i=ts" alt="TypeScript" className="w-full h-full" />,
  React: <img src="https://skillicons.dev/icons?i=react" alt="React" className="w-full h-full" />,
  "Next.js": <img src="https://skillicons.dev/icons?i=nextjs" alt="Next.js" className="w-full h-full" />,
  "Node.js": <img src="https://skillicons.dev/icons?i=nodejs" alt="Node.js" className="w-full h-full" />,
  PyTorch: <img src="https://skillicons.dev/icons?i=pytorch" alt="PyTorch" className="w-full h-full" />,
  TensorFlow: <img src="https://skillicons.dev/icons?i=tensorflow" alt="TensorFlow" className="w-full h-full" />,
  FastAPI: <img src="https://skillicons.dev/icons?i=fastapi" alt="FastAPI" className="w-full h-full" />,
  SQL: <img src="https://skillicons.dev/icons?i=mysql" alt="SQL" className="w-full h-full" />,
  PostgreSQL: <img src="https://skillicons.dev/icons?i=postgres" alt="PostgreSQL" className="w-full h-full" />,
  "Tailwind CSS": <img src="https://skillicons.dev/icons?i=tailwind" alt="Tailwind CSS" className="w-full h-full" />,
  Figma: <img src="https://skillicons.dev/icons?i=figma" alt="Figma" className="w-full h-full" />,
  Docker: <img src="https://skillicons.dev/icons?i=docker" alt="Docker" className="w-full h-full" />,
  AWS: <img src="https://skillicons.dev/icons?i=aws" alt="AWS" className="w-full h-full" />,
  Git: <img src="https://skillicons.dev/icons?i=git" alt="Git" className="w-full h-full" />,
  Github: <img src="https://skillicons.dev/icons?i=github" alt="Github" className="w-full h-full" />,
  Arch: <img src="https://skillicons.dev/icons?i=arch" alt="Arch Linux" className="w-full h-full" />,
  Linux: <img src="https://skillicons.dev/icons?i=linux" alt="Linux" className="w-full h-full" />,
  Ubuntu: <img src="https://skillicons.dev/icons?i=ubuntu" alt="Ubuntu" className="w-full h-full" />,
  HTML: <img src="https://skillicons.dev/icons?i=html" alt="HTML" className="w-full h-full" />,
  CSS: <img src="https://skillicons.dev/icons?i=css" alt="CSS" className="w-full h-full" />,
  Photoshop: <img src="https://skillicons.dev/icons?i=ps" alt="Photoshop" className="w-full h-full" />,
  Gmail: <img src="https://skillicons.dev/icons?i=gmail" alt="Gmail" className="w-full h-full" />,
  npm: <img src="https://skillicons.dev/icons?i=npm" alt="npm" className="w-full h-full" />,
  Notion: <img src="https://skillicons.dev/icons?i=notion" alt="Notion" className="w-full h-full" />,
  MATLAB: <img src="https://skillicons.dev/icons?i=matlab" alt="MATLAB" className="w-full h-full" />,
  MongoDB: <img src="https://skillicons.dev/icons?i=mongodb" alt="MongoDB" className="w-full h-full" />,
  Markdown: <img src="https://skillicons.dev/icons?i=markdown" alt="Markdown" className="w-full h-full" />,
  Kafka: <img src="https://skillicons.dev/icons?i=kafka" alt="Kafka" className="w-full h-full" />,
  Bash: <img src="https://skillicons.dev/icons?i=bash" alt="Bash" className="w-full h-full" />,
  Obsidian: <img src="https://skillicons.dev/icons?i=obsidian" alt="Obsidian" className="w-full h-full" />,
};
